name: Bitcoin Price Alert
on:
  workflow_dispatch:
  schedule:
    - cron: 0 * * * *
jobs:
  bitcoin-price:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Get Bitcoin Price
        env:
          COINMARKETCAP_API_KEY: ${{ secrets.COINMARKETCAP_API_KEY }}
        run: |
          curl -s -X GET "https://pro-api.coinmarketcap.com/v1/cryptocurrency/quotes/latest" \
            -H "Accepts: application/json" \
            -H "X-CMC_PRO_API_KEY: ${COINMARKETCAP_API_KEY}" \
            -d "symbol=BTC&convert=USD" > bitcoin_price.json
      - name: Extract Bitcoin Price
        run: |
          bitcoin_price=$(jq -r '.data.BTC.quote.USD.price' bitcoin_price.json)
          echo "BITCOIN_PRICE=$bitcoin_price" >> $GITHUB_ENV
      - name: Send Telegram Message
        env:
          BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          BITCOIN_PRICE: