name: Main Bot Ping Test
on:
  workflow_dispatch:
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
    - name: Ping the bot
      env:
        TELEGRAM_WORKER_URL: ${{ secrets.TELEGRAM_WORKER_URL }}
      run: |
        curl -X POST -H "Content-Type: application/json" -d '{}' $TELEGRAM_WORKER_URL/ping