name: Deploy Sandbox Clone
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Create new private repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_NAME: bot-sandbox
        run: |
          curl -X POST \
          https://api.github.com/user/repos \
          -H 'Authorization: Bearer ${GITHUB_TOKEN}' \
          -H 'Content-Type: application/json' \
          -d '{"name":"${REPO_NAME}","private":true}'
      - name: Push files to new repository
        uses: cpina/github-action-push-to-another-repository@v1
        with:
          source-repo: ${{ github.repository }}
          destination-repo: ${{ github.repository_owner }}/${{ env.REPO_NAME }}
          github-token: ${{ secrets.GITHUB_TOKEN }}