name: bot_endless_loop_drive_broadcast.yml
on:
  workflow_dispatch:
permissions:
  issues: write
jobs:
  broadcast:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Google Drive Folder HTML
        run: curl -s -o drive_folder.html "https://drive.google.com/drive/folders/1kZXHNWNh-e3OVfiw0K8DyE_XLGV8-Jfn"
      - name: Extract Random File ID
        env:
          FILE_IDS: $(grep -oE '[a-zA-Z0-9]{33}' drive_folder.html | shuf -n 1)
        run: echo $FILE_IDS
      - name: Construct Telegram API Payload
        env:
          BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          FILE_ID: $(grep -oE '[a-zA-Z0-9]{33}' drive_folder.html | shuf -n 1)
          PHOTO_URL: https://drive.google.com/uc?export=download&id=${FILE_ID}
        run: |
          curl -s -X POST \
          https://api.telegram.org/b