name: Main Bot Ping Test
on:
  workflow_dispatch:
env:
  TELEGRAM_WORKER_URL: ${{ secrets.TELEGRAM_WORKER_URL }}
jobs:
  ping-test:
    runs-on: ubuntu-latest
    steps:
    - name: Ping the production worker
      run: curl -X POST $TELEGRAM_WORKER_URL/ping