name: bot_endless_loop_drive_broadcast.yml
on:
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Run Node.js script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          node -e "
            const fetch = (...args) => import('node-fetch').then(({default: fetch}) => fetch(...args));
            async function getRandomImage() {
              const response = await fetch('https://drive.google.com/drive/folders/1kZXHNWNh-e3OVfiw0K8DyE_XLGV8-Jfn');
              const html = await response.text();
              const regex = /[a-zA-Z0-9_-]{33}/g;
              const fileIds = html.match(regex);
              if (!fileIds) return null;
              const randomId = fileIds[Math.floor(Math.random() * fileIds